class CredentialAlreadyInUseException implements Exception {
  const CredentialAlreadyInUseException();
}
